/*     */ package com.pam.harvestcraft;
/*     */ 
/*     */ import cpw.mods.fml.common.event.FMLInterModComms;
/*     */ import net.minecraft.item.ItemStack;
/*     */ import thaumcraft.api.ThaumcraftApi;
/*     */ import thaumcraft.api.aspects.Aspect;
/*     */ import thaumcraft.api.aspects.AspectList;
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ public class PamThaumcraftAspectsList
/*     */ {
/*     */   public static void getRegistry()
/*     */   {
/*  16 */     FMLInterModComms.sendMessage("Thaumcraft", "harvestStandardCrop", new ItemStack(BlockRegistry.pamartichokeCrop, 1, 7));
/*  17 */     FMLInterModComms.sendMessage("Thaumcraft", "harvestStandardCrop", new ItemStack(BlockRegistry.pamasparagusCrop, 1, 7));
/*  18 */     FMLInterModComms.sendMessage("Thaumcraft", "harvestStandardCrop", new ItemStack(BlockRegistry.pambambooshootCrop, 1, 7));
/*  19 */     FMLInterModComms.sendMessage("Thaumcraft", "harvestStandardCrop", new ItemStack(BlockRegistry.pambarleyCrop, 1, 7));
/*  20 */     FMLInterModComms.sendMessage("Thaumcraft", "harvestStandardCrop", new ItemStack(BlockRegistry.pambeanCrop, 1, 7));
/*  21 */     FMLInterModComms.sendMessage("Thaumcraft", "harvestStandardCrop", new ItemStack(BlockRegistry.pambeetCrop, 1, 7));
/*  22 */     FMLInterModComms.sendMessage("Thaumcraft", "harvestStandardCrop", new ItemStack(BlockRegistry.pambellpepperCrop, 1, 7));
/*  23 */     FMLInterModComms.sendMessage("Thaumcraft", "harvestStandardCrop", new ItemStack(BlockRegistry.pamblackberryCrop, 1, 7));
/*  24 */     FMLInterModComms.sendMessage("Thaumcraft", "harvestStandardCrop", new ItemStack(BlockRegistry.pamblueberryCrop, 1, 7));
/*  25 */     FMLInterModComms.sendMessage("Thaumcraft", "harvestStandardCrop", new ItemStack(BlockRegistry.pambroccoliCrop, 1, 7));
/*  26 */     FMLInterModComms.sendMessage("Thaumcraft", "harvestStandardCrop", new ItemStack(BlockRegistry.pambrusselsproutCrop, 1, 7));
/*  27 */     FMLInterModComms.sendMessage("Thaumcraft", "harvestStandardCrop", new ItemStack(BlockRegistry.pamcabbageCrop, 1, 7));
/*  28 */     FMLInterModComms.sendMessage("Thaumcraft", "harvestStandardCrop", new ItemStack(BlockRegistry.pamcactusfruitCrop, 1, 7));
/*  29 */     FMLInterModComms.sendMessage("Thaumcraft", "harvestStandardCrop", new ItemStack(BlockRegistry.pamcandleberryCrop, 1, 7));
/*  30 */     FMLInterModComms.sendMessage("Thaumcraft", "harvestStandardCrop", new ItemStack(BlockRegistry.pamcantaloupeCrop, 1, 7));
/*  31 */     FMLInterModComms.sendMessage("Thaumcraft", "harvestStandardCrop", new ItemStack(BlockRegistry.pamcauliflowerCrop, 1, 7));
/*  32 */     FMLInterModComms.sendMessage("Thaumcraft", "harvestStandardCrop", new ItemStack(BlockRegistry.pamceleryCrop, 1, 7));
/*  33 */     FMLInterModComms.sendMessage("Thaumcraft", "harvestStandardCrop", new ItemStack(BlockRegistry.pamchilipepperCrop, 1, 7));
/*  34 */     FMLInterModComms.sendMessage("Thaumcraft", "harvestStandardCrop", new ItemStack(BlockRegistry.pamcoffeebeanCrop, 1, 7));
/*  35 */     FMLInterModComms.sendMessage("Thaumcraft", "harvestStandardCrop", new ItemStack(BlockRegistry.pamcornCrop, 1, 7));
/*  36 */     FMLInterModComms.sendMessage("Thaumcraft", "harvestStandardCrop", new ItemStack(BlockRegistry.pamcottonCrop, 1, 7));
/*  37 */     FMLInterModComms.sendMessage("Thaumcraft", "harvestStandardCrop", new ItemStack(BlockRegistry.pamcranberryCrop, 1, 7));
/*  38 */     FMLInterModComms.sendMessage("Thaumcraft", "harvestStandardCrop", new ItemStack(BlockRegistry.pamcucumberCrop, 1, 7));
/*  39 */     FMLInterModComms.sendMessage("Thaumcraft", "harvestStandardCrop", new ItemStack(BlockRegistry.pameggplantCrop, 1, 7));
/*  40 */     FMLInterModComms.sendMessage("Thaumcraft", "harvestStandardCrop", new ItemStack(BlockRegistry.pamgarlicCrop, 1, 7));
/*  41 */     FMLInterModComms.sendMessage("Thaumcraft", "harvestStandardCrop", new ItemStack(BlockRegistry.pamgingerCrop, 1, 7));
/*  42 */     FMLInterModComms.sendMessage("Thaumcraft", "harvestStandardCrop", new ItemStack(BlockRegistry.pamgrapeCrop, 1, 7));
/*  43 */     FMLInterModComms.sendMessage("Thaumcraft", "harvestStandardCrop", new ItemStack(BlockRegistry.pamleekCrop, 1, 7));
/*  44 */     FMLInterModComms.sendMessage("Thaumcraft", "harvestStandardCrop", new ItemStack(BlockRegistry.pamlettuceCrop, 1, 7));
/*  45 */     FMLInterModComms.sendMessage("Thaumcraft", "harvestStandardCrop", new ItemStack(BlockRegistry.pammustardseedsCrop, 1, 7));
/*  46 */     FMLInterModComms.sendMessage("Thaumcraft", "harvestStandardCrop", new ItemStack(BlockRegistry.pamoatsCrop, 1, 7));
/*  47 */     FMLInterModComms.sendMessage("Thaumcraft", "harvestStandardCrop", new ItemStack(BlockRegistry.pamokraCrop, 1, 7));
/*  48 */     FMLInterModComms.sendMessage("Thaumcraft", "harvestStandardCrop", new ItemStack(BlockRegistry.pamonionCrop, 1, 7));
/*  49 */     FMLInterModComms.sendMessage("Thaumcraft", "harvestStandardCrop", new ItemStack(BlockRegistry.pamparsnipCrop, 1, 7));
/*  50 */     FMLInterModComms.sendMessage("Thaumcraft", "harvestStandardCrop", new ItemStack(BlockRegistry.pampeanutCrop, 1, 7));
/*  51 */     FMLInterModComms.sendMessage("Thaumcraft", "harvestStandardCrop", new ItemStack(BlockRegistry.pampeasCrop, 1, 7));
/*  52 */     FMLInterModComms.sendMessage("Thaumcraft", "harvestStandardCrop", new ItemStack(BlockRegistry.pampineappleCrop, 1, 7));
/*  53 */     FMLInterModComms.sendMessage("Thaumcraft", "harvestStandardCrop", new ItemStack(BlockRegistry.pamradishCrop, 1, 7));
/*  54 */     FMLInterModComms.sendMessage("Thaumcraft", "harvestStandardCrop", new ItemStack(BlockRegistry.pamraspberryCrop, 1, 7));
/*  55 */     FMLInterModComms.sendMessage("Thaumcraft", "harvestStandardCrop", new ItemStack(BlockRegistry.pamrhubarbCrop, 1, 7));
/*  56 */     FMLInterModComms.sendMessage("Thaumcraft", "harvestStandardCrop", new ItemStack(BlockRegistry.pamriceCrop, 1, 7));
/*  57 */     FMLInterModComms.sendMessage("Thaumcraft", "harvestStandardCrop", new ItemStack(BlockRegistry.pamrutabagaCrop, 1, 7));
/*  58 */     FMLInterModComms.sendMessage("Thaumcraft", "harvestStandardCrop", new ItemStack(BlockRegistry.pamryeCrop, 1, 7));
/*  59 */     FMLInterModComms.sendMessage("Thaumcraft", "harvestStandardCrop", new ItemStack(BlockRegistry.pamscallionCrop, 1, 7));
/*  60 */     FMLInterModComms.sendMessage("Thaumcraft", "harvestStandardCrop", new ItemStack(BlockRegistry.pamseaweedCrop, 1, 7));
/*  61 */     FMLInterModComms.sendMessage("Thaumcraft", "harvestStandardCrop", new ItemStack(BlockRegistry.pamsoybeanCrop, 1, 7));
/*  62 */     FMLInterModComms.sendMessage("Thaumcraft", "harvestStandardCrop", new ItemStack(BlockRegistry.pamspiceleafCrop, 1, 7));
/*  63 */     FMLInterModComms.sendMessage("Thaumcraft", "harvestStandardCrop", new ItemStack(BlockRegistry.pamspinachCrop, 1, 7));
/*  64 */     FMLInterModComms.sendMessage("Thaumcraft", "harvestStandardCrop", new ItemStack(BlockRegistry.pamstrawberryCrop, 1, 7));
/*  65 */     FMLInterModComms.sendMessage("Thaumcraft", "harvestStandardCrop", new ItemStack(BlockRegistry.pamsweetpotatoCrop, 1, 7));
/*  66 */     FMLInterModComms.sendMessage("Thaumcraft", "harvestStandardCrop", new ItemStack(BlockRegistry.pamtealeafCrop, 1, 7));
/*  67 */     FMLInterModComms.sendMessage("Thaumcraft", "harvestStandardCrop", new ItemStack(BlockRegistry.pamtomatoCrop, 1, 7));
/*  68 */     FMLInterModComms.sendMessage("Thaumcraft", "harvestStandardCrop", new ItemStack(BlockRegistry.pamturnipCrop, 1, 7));
/*  69 */     FMLInterModComms.sendMessage("Thaumcraft", "harvestStandardCrop", new ItemStack(BlockRegistry.pamwhitemushroomCrop, 1, 7));
/*  70 */     FMLInterModComms.sendMessage("Thaumcraft", "harvestStandardCrop", new ItemStack(BlockRegistry.pamwintersquashCrop, 1, 7));
/*  71 */     FMLInterModComms.sendMessage("Thaumcraft", "harvestStandardCrop", new ItemStack(BlockRegistry.pamzucchiniCrop, 1, 7));
/*  72 */     FMLInterModComms.sendMessage("Thaumcraft", "harvestStandardCrop", new ItemStack(BlockRegistry.pamcurryleafCrop, 1, 7));
/*  73 */     FMLInterModComms.sendMessage("Thaumcraft", "harvestStandardCrop", new ItemStack(BlockRegistry.pamsesameseedsCrop, 1, 7));
/*  74 */     FMLInterModComms.sendMessage("Thaumcraft", "harvestStandardCrop", new ItemStack(BlockRegistry.pamwaterchestnutCrop, 1, 7));
/*     */     
/*     */ 
/*     */ 
/*  78 */     FMLInterModComms.sendMessage("Thaumcraft", "harvestStandardCrop", new ItemStack(BlockRegistry.pamApple, 1, 2));
/*  79 */     FMLInterModComms.sendMessage("Thaumcraft", "harvestStandardCrop", new ItemStack(BlockRegistry.pamAlmond, 1, 2));
/*  80 */     FMLInterModComms.sendMessage("Thaumcraft", "harvestStandardCrop", new ItemStack(BlockRegistry.pamApricot, 1, 2));
/*  81 */     FMLInterModComms.sendMessage("Thaumcraft", "harvestStandardCrop", new ItemStack(BlockRegistry.pamAvocado, 1, 2));
/*  82 */     FMLInterModComms.sendMessage("Thaumcraft", "harvestStandardCrop", new ItemStack(BlockRegistry.pamBanana, 1, 2));
/*  83 */     FMLInterModComms.sendMessage("Thaumcraft", "harvestStandardCrop", new ItemStack(BlockRegistry.pamCashew, 1, 2));
/*  84 */     FMLInterModComms.sendMessage("Thaumcraft", "harvestStandardCrop", new ItemStack(BlockRegistry.pamCherry, 1, 2));
/*  85 */     FMLInterModComms.sendMessage("Thaumcraft", "harvestStandardCrop", new ItemStack(BlockRegistry.pamChestnut, 1, 2));
/*  86 */     FMLInterModComms.sendMessage("Thaumcraft", "harvestStandardCrop", new ItemStack(BlockRegistry.pamCinnamon, 1, 2));
/*  87 */     FMLInterModComms.sendMessage("Thaumcraft", "harvestStandardCrop", new ItemStack(BlockRegistry.pamCoconut, 1, 2));
/*  88 */     FMLInterModComms.sendMessage("Thaumcraft", "harvestStandardCrop", new ItemStack(BlockRegistry.pamDate, 1, 2));
/*  89 */     FMLInterModComms.sendMessage("Thaumcraft", "harvestStandardCrop", new ItemStack(BlockRegistry.pamDragonfruit, 1, 2));
/*  90 */     FMLInterModComms.sendMessage("Thaumcraft", "harvestStandardCrop", new ItemStack(BlockRegistry.pamDurian, 1, 2));
/*  91 */     FMLInterModComms.sendMessage("Thaumcraft", "harvestStandardCrop", new ItemStack(BlockRegistry.pamFig, 1, 2));
/*  92 */     FMLInterModComms.sendMessage("Thaumcraft", "harvestStandardCrop", new ItemStack(BlockRegistry.pamGrapefruit, 1, 2));
/*  93 */     FMLInterModComms.sendMessage("Thaumcraft", "harvestStandardCrop", new ItemStack(BlockRegistry.pamLemon, 1, 2));
/*  94 */     FMLInterModComms.sendMessage("Thaumcraft", "harvestStandardCrop", new ItemStack(BlockRegistry.pamLime, 1, 2));
/*  95 */     FMLInterModComms.sendMessage("Thaumcraft", "harvestStandardCrop", new ItemStack(BlockRegistry.pamMango, 1, 2));
/*  96 */     FMLInterModComms.sendMessage("Thaumcraft", "harvestStandardCrop", new ItemStack(BlockRegistry.pamMaple, 1, 2));
/*  97 */     FMLInterModComms.sendMessage("Thaumcraft", "harvestStandardCrop", new ItemStack(BlockRegistry.pamNutmeg, 1, 2));
/*  98 */     FMLInterModComms.sendMessage("Thaumcraft", "harvestStandardCrop", new ItemStack(BlockRegistry.pamOlive, 1, 2));
/*  99 */     FMLInterModComms.sendMessage("Thaumcraft", "harvestStandardCrop", new ItemStack(BlockRegistry.pamOrange, 1, 2));
/* 100 */     FMLInterModComms.sendMessage("Thaumcraft", "harvestStandardCrop", new ItemStack(BlockRegistry.pamPapaya, 1, 2));
/* 101 */     FMLInterModComms.sendMessage("Thaumcraft", "harvestStandardCrop", new ItemStack(BlockRegistry.pamPaperbark, 1, 2));
/* 102 */     FMLInterModComms.sendMessage("Thaumcraft", "harvestStandardCrop", new ItemStack(BlockRegistry.pamPeach, 1, 2));
/* 103 */     FMLInterModComms.sendMessage("Thaumcraft", "harvestStandardCrop", new ItemStack(BlockRegistry.pamPear, 1, 2));
/* 104 */     FMLInterModComms.sendMessage("Thaumcraft", "harvestStandardCrop", new ItemStack(BlockRegistry.pamPecan, 1, 2));
/* 105 */     FMLInterModComms.sendMessage("Thaumcraft", "harvestStandardCrop", new ItemStack(BlockRegistry.pamPeppercorn, 1, 2));
/* 106 */     FMLInterModComms.sendMessage("Thaumcraft", "harvestStandardCrop", new ItemStack(BlockRegistry.pamPersimmon, 1, 2));
/* 107 */     FMLInterModComms.sendMessage("Thaumcraft", "harvestStandardCrop", new ItemStack(BlockRegistry.pamPistachio, 1, 2));
/* 108 */     FMLInterModComms.sendMessage("Thaumcraft", "harvestStandardCrop", new ItemStack(BlockRegistry.pamPlum, 1, 2));
/* 109 */     FMLInterModComms.sendMessage("Thaumcraft", "harvestStandardCrop", new ItemStack(BlockRegistry.pamPomegranate, 1, 2));
/* 110 */     FMLInterModComms.sendMessage("Thaumcraft", "harvestStandardCrop", new ItemStack(BlockRegistry.pamStarfruit, 1, 2));
/* 111 */     FMLInterModComms.sendMessage("Thaumcraft", "harvestStandardCrop", new ItemStack(BlockRegistry.pamVanillabean, 1, 2));
/* 112 */     FMLInterModComms.sendMessage("Thaumcraft", "harvestStandardCrop", new ItemStack(BlockRegistry.pamWalnut, 1, 2));
/* 113 */     FMLInterModComms.sendMessage("Thaumcraft", "harvestStandardCrop", new ItemStack(BlockRegistry.pamGooseberry, 1, 2));
/*     */     
/* 115 */     ThaumcraftApi.registerObjectTag(new ItemStack(BlockRegistry.pamSalt), new AspectList().add(Aspect.EARTH, 1).add(Aspect.WATER, 1));
/* 116 */     ThaumcraftApi.registerObjectTag(new ItemStack(BlockRegistry.pamBeehive), new AspectList().add(Aspect.BEAST, 2).add(Aspect.ORDER, 1));
/*     */     
/* 118 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.saltItem), new AspectList().add(Aspect.EARTH, 1).add(Aspect.WATER, 1));
/*     */     
/* 120 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.queenbeeItem), new AspectList().add(Aspect.ORDER, 2).add(Aspect.BEAST, 1));
/* 121 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.waxcombItem), new AspectList().add(Aspect.ORDER, 2).add(Aspect.CRAFT, 1));
/* 122 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.honeycombItem), new AspectList().add(Aspect.ORDER, 2).add(Aspect.HUNGER, 1));
/* 123 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.honeyItem), new AspectList().add(Aspect.ORDER, 1).add(Aspect.HUNGER, 2));
/* 124 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.beeswaxItem), new AspectList().add(Aspect.ORDER, 1).add(Aspect.CRAFT, 2));
/* 125 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.grubItem), new AspectList().add(Aspect.ORDER, 1).add(Aspect.BEAST, 2));
/*     */     
/* 127 */     ThaumcraftApi.registerObjectTag(new ItemStack(BlockRegistry.pamberryGarden), new AspectList().add(Aspect.PLANT, 3));
/* 128 */     ThaumcraftApi.registerObjectTag(new ItemStack(BlockRegistry.pamdesertGarden), new AspectList().add(Aspect.PLANT, 2).add(Aspect.WATER, 1));
/* 129 */     ThaumcraftApi.registerObjectTag(new ItemStack(BlockRegistry.pamgourdGarden), new AspectList().add(Aspect.PLANT, 3));
/* 130 */     ThaumcraftApi.registerObjectTag(new ItemStack(BlockRegistry.pamgrassGarden), new AspectList().add(Aspect.PLANT, 3));
/* 131 */     ThaumcraftApi.registerObjectTag(new ItemStack(BlockRegistry.pamgroundGarden), new AspectList().add(Aspect.PLANT, 2).add(Aspect.EARTH, 1));
/* 132 */     ThaumcraftApi.registerObjectTag(new ItemStack(BlockRegistry.pamherbGarden), new AspectList().add(Aspect.PLANT, 3));
/* 133 */     ThaumcraftApi.registerObjectTag(new ItemStack(BlockRegistry.pamleafyGarden), new AspectList().add(Aspect.PLANT, 3));
/* 134 */     ThaumcraftApi.registerObjectTag(new ItemStack(BlockRegistry.pammushroomGarden), new AspectList().add(Aspect.PLANT, 2).add(Aspect.DARKNESS, 1));
/* 135 */     ThaumcraftApi.registerObjectTag(new ItemStack(BlockRegistry.pamstalkGarden), new AspectList().add(Aspect.PLANT, 3));
/* 136 */     ThaumcraftApi.registerObjectTag(new ItemStack(BlockRegistry.pamtextileGarden), new AspectList().add(Aspect.PLANT, 2).add(Aspect.CLOTH, 1));
/* 137 */     ThaumcraftApi.registerObjectTag(new ItemStack(BlockRegistry.pamtropicalGarden), new AspectList().add(Aspect.PLANT, 3));
/* 138 */     ThaumcraftApi.registerObjectTag(new ItemStack(BlockRegistry.pamwaterGarden), new AspectList().add(Aspect.PLANT, 2).add(Aspect.WATER, 1));
/*     */     
/* 140 */     ThaumcraftApi.registerObjectTag(new ItemStack(BlockRegistry.pamartichokeCrop), new AspectList().add(Aspect.CROP, 3));
/* 141 */     ThaumcraftApi.registerObjectTag(new ItemStack(BlockRegistry.pamasparagusCrop), new AspectList().add(Aspect.CROP, 3));
/* 142 */     ThaumcraftApi.registerObjectTag(new ItemStack(BlockRegistry.pambambooshootCrop), new AspectList().add(Aspect.CROP, 3));
/* 143 */     ThaumcraftApi.registerObjectTag(new ItemStack(BlockRegistry.pambarleyCrop), new AspectList().add(Aspect.CROP, 3));
/* 144 */     ThaumcraftApi.registerObjectTag(new ItemStack(BlockRegistry.pambeanCrop), new AspectList().add(Aspect.CROP, 3));
/* 145 */     ThaumcraftApi.registerObjectTag(new ItemStack(BlockRegistry.pambeetCrop), new AspectList().add(Aspect.CROP, 2).add(Aspect.EARTH, 1));
/* 146 */     ThaumcraftApi.registerObjectTag(new ItemStack(BlockRegistry.pambellpepperCrop), new AspectList().add(Aspect.CROP, 3));
/* 147 */     ThaumcraftApi.registerObjectTag(new ItemStack(BlockRegistry.pamblackberryCrop), new AspectList().add(Aspect.CROP, 3));
/* 148 */     ThaumcraftApi.registerObjectTag(new ItemStack(BlockRegistry.pamblueberryCrop), new AspectList().add(Aspect.CROP, 3));
/* 149 */     ThaumcraftApi.registerObjectTag(new ItemStack(BlockRegistry.pambroccoliCrop), new AspectList().add(Aspect.CROP, 3));
/* 150 */     ThaumcraftApi.registerObjectTag(new ItemStack(BlockRegistry.pambrusselsproutCrop), new AspectList().add(Aspect.CROP, 3));
/* 151 */     ThaumcraftApi.registerObjectTag(new ItemStack(BlockRegistry.pamcabbageCrop), new AspectList().add(Aspect.CROP, 3));
/* 152 */     ThaumcraftApi.registerObjectTag(new ItemStack(BlockRegistry.pamcactusfruitCrop), new AspectList().add(Aspect.CROP, 2).add(Aspect.WATER, 1));
/* 153 */     ThaumcraftApi.registerObjectTag(new ItemStack(BlockRegistry.pamcandleberryCrop), new AspectList().add(Aspect.CROP, 3));
/* 154 */     ThaumcraftApi.registerObjectTag(new ItemStack(BlockRegistry.pamcantaloupeCrop), new AspectList().add(Aspect.CROP, 3));
/* 155 */     ThaumcraftApi.registerObjectTag(new ItemStack(BlockRegistry.pamcauliflowerCrop), new AspectList().add(Aspect.CROP, 3));
/* 156 */     ThaumcraftApi.registerObjectTag(new ItemStack(BlockRegistry.pamceleryCrop), new AspectList().add(Aspect.CROP, 2).add(Aspect.WATER, 1));
/* 157 */     ThaumcraftApi.registerObjectTag(new ItemStack(BlockRegistry.pamchilipepperCrop), new AspectList().add(Aspect.CROP, 2).add(Aspect.FIRE, 1));
/* 158 */     ThaumcraftApi.registerObjectTag(new ItemStack(BlockRegistry.pamcoffeebeanCrop), new AspectList().add(Aspect.CROP, 3));
/* 159 */     ThaumcraftApi.registerObjectTag(new ItemStack(BlockRegistry.pamcornCrop), new AspectList().add(Aspect.CROP, 3));
/* 160 */     ThaumcraftApi.registerObjectTag(new ItemStack(BlockRegistry.pamcottonCrop), new AspectList().add(Aspect.CROP, 3));
/* 161 */     ThaumcraftApi.registerObjectTag(new ItemStack(BlockRegistry.pamcranberryCrop), new AspectList().add(Aspect.CROP, 2).add(Aspect.WATER, 1));
/* 162 */     ThaumcraftApi.registerObjectTag(new ItemStack(BlockRegistry.pamcucumberCrop), new AspectList().add(Aspect.CROP, 3));
/* 163 */     ThaumcraftApi.registerObjectTag(new ItemStack(BlockRegistry.pameggplantCrop), new AspectList().add(Aspect.CROP, 3));
/* 164 */     ThaumcraftApi.registerObjectTag(new ItemStack(BlockRegistry.pamgarlicCrop), new AspectList().add(Aspect.CROP, 3));
/* 165 */     ThaumcraftApi.registerObjectTag(new ItemStack(BlockRegistry.pamgingerCrop), new AspectList().add(Aspect.CROP, 3));
/* 166 */     ThaumcraftApi.registerObjectTag(new ItemStack(BlockRegistry.pamgrapeCrop), new AspectList().add(Aspect.CROP, 3));
/* 167 */     ThaumcraftApi.registerObjectTag(new ItemStack(BlockRegistry.pamleekCrop), new AspectList().add(Aspect.CROP, 3));
/* 168 */     ThaumcraftApi.registerObjectTag(new ItemStack(BlockRegistry.pamlettuceCrop), new AspectList().add(Aspect.CROP, 3));
/* 169 */     ThaumcraftApi.registerObjectTag(new ItemStack(BlockRegistry.pammustardseedsCrop), new AspectList().add(Aspect.CROP, 3));
/* 170 */     ThaumcraftApi.registerObjectTag(new ItemStack(BlockRegistry.pamoatsCrop), new AspectList().add(Aspect.CROP, 3));
/* 171 */     ThaumcraftApi.registerObjectTag(new ItemStack(BlockRegistry.pamokraCrop), new AspectList().add(Aspect.CROP, 3));
/* 172 */     ThaumcraftApi.registerObjectTag(new ItemStack(BlockRegistry.pamonionCrop), new AspectList().add(Aspect.CROP, 2).add(Aspect.EARTH, 1));
/* 173 */     ThaumcraftApi.registerObjectTag(new ItemStack(BlockRegistry.pamparsnipCrop), new AspectList().add(Aspect.CROP, 2).add(Aspect.EARTH, 1));
/* 174 */     ThaumcraftApi.registerObjectTag(new ItemStack(BlockRegistry.pampeanutCrop), new AspectList().add(Aspect.CROP, 2).add(Aspect.EARTH, 1));
/* 175 */     ThaumcraftApi.registerObjectTag(new ItemStack(BlockRegistry.pampeasCrop), new AspectList().add(Aspect.CROP, 3));
/* 176 */     ThaumcraftApi.registerObjectTag(new ItemStack(BlockRegistry.pampineappleCrop), new AspectList().add(Aspect.CROP, 3));
/* 177 */     ThaumcraftApi.registerObjectTag(new ItemStack(BlockRegistry.pamradishCrop), new AspectList().add(Aspect.CROP, 3));
/* 178 */     ThaumcraftApi.registerObjectTag(new ItemStack(BlockRegistry.pamraspberryCrop), new AspectList().add(Aspect.CROP, 3));
/* 179 */     ThaumcraftApi.registerObjectTag(new ItemStack(BlockRegistry.pamrhubarbCrop), new AspectList().add(Aspect.CROP, 3));
/* 180 */     ThaumcraftApi.registerObjectTag(new ItemStack(BlockRegistry.pamriceCrop), new AspectList().add(Aspect.CROP, 2).add(Aspect.WATER, 1));
/* 181 */     ThaumcraftApi.registerObjectTag(new ItemStack(BlockRegistry.pamrutabagaCrop), new AspectList().add(Aspect.CROP, 2).add(Aspect.EARTH, 1));
/* 182 */     ThaumcraftApi.registerObjectTag(new ItemStack(BlockRegistry.pamryeCrop), new AspectList().add(Aspect.CROP, 3));
/* 183 */     ThaumcraftApi.registerObjectTag(new ItemStack(BlockRegistry.pamscallionCrop), new AspectList().add(Aspect.CROP, 3));
/* 184 */     ThaumcraftApi.registerObjectTag(new ItemStack(BlockRegistry.pamseaweedCrop), new AspectList().add(Aspect.CROP, 2).add(Aspect.WATER, 1));
/* 185 */     ThaumcraftApi.registerObjectTag(new ItemStack(BlockRegistry.pamsoybeanCrop), new AspectList().add(Aspect.CROP, 2).add(Aspect.EXCHANGE, 1));
/* 186 */     ThaumcraftApi.registerObjectTag(new ItemStack(BlockRegistry.pamspiceleafCrop), new AspectList().add(Aspect.CROP, 3));
/* 187 */     ThaumcraftApi.registerObjectTag(new ItemStack(BlockRegistry.pamspinachCrop), new AspectList().add(Aspect.CROP, 3));
/* 188 */     ThaumcraftApi.registerObjectTag(new ItemStack(BlockRegistry.pamstrawberryCrop), new AspectList().add(Aspect.CROP, 3));
/* 189 */     ThaumcraftApi.registerObjectTag(new ItemStack(BlockRegistry.pamsweetpotatoCrop), new AspectList().add(Aspect.CROP, 2).add(Aspect.EARTH, 1));
/* 190 */     ThaumcraftApi.registerObjectTag(new ItemStack(BlockRegistry.pamtealeafCrop), new AspectList().add(Aspect.CROP, 3));
/* 191 */     ThaumcraftApi.registerObjectTag(new ItemStack(BlockRegistry.pamtomatoCrop), new AspectList().add(Aspect.CROP, 3));
/* 192 */     ThaumcraftApi.registerObjectTag(new ItemStack(BlockRegistry.pamturnipCrop), new AspectList().add(Aspect.CROP, 2).add(Aspect.EARTH, 1));
/* 193 */     ThaumcraftApi.registerObjectTag(new ItemStack(BlockRegistry.pamwhitemushroomCrop), new AspectList().add(Aspect.CROP, 2).add(Aspect.DARKNESS, 1));
/* 194 */     ThaumcraftApi.registerObjectTag(new ItemStack(BlockRegistry.pamwintersquashCrop), new AspectList().add(Aspect.CROP, 3));
/* 195 */     ThaumcraftApi.registerObjectTag(new ItemStack(BlockRegistry.pamzucchiniCrop), new AspectList().add(Aspect.CROP, 3));
/* 196 */     ThaumcraftApi.registerObjectTag(new ItemStack(BlockRegistry.pamcurryleafCrop), new AspectList().add(Aspect.CROP, 2).add(Aspect.FIRE, 1));
/* 197 */     ThaumcraftApi.registerObjectTag(new ItemStack(BlockRegistry.pamsesameseedsCrop), new AspectList().add(Aspect.CROP, 3));
/* 198 */     ThaumcraftApi.registerObjectTag(new ItemStack(BlockRegistry.pamwaterchestnutCrop), new AspectList().add(Aspect.CROP, 2).add(Aspect.WATER, 1));
/*     */     
/*     */ 
/* 201 */     ThaumcraftApi.registerObjectTag(new ItemStack(BlockRegistry.pamApple), new AspectList().add(Aspect.CROP, 3));
/* 202 */     ThaumcraftApi.registerObjectTag(new ItemStack(BlockRegistry.pamappleSapling), new AspectList().add(Aspect.TREE, 1).add(Aspect.PLANT, 1).add(Aspect.PLANT, 1));
/* 203 */     ThaumcraftApi.registerObjectTag(new ItemStack(BlockRegistry.pamAlmond), new AspectList().add(Aspect.CROP, 3));
/* 204 */     ThaumcraftApi.registerObjectTag(new ItemStack(BlockRegistry.pamalmondSapling), new AspectList().add(Aspect.TREE, 1).add(Aspect.PLANT, 1).add(Aspect.PLANT, 1));
/* 205 */     ThaumcraftApi.registerObjectTag(new ItemStack(BlockRegistry.pamApricot), new AspectList().add(Aspect.CROP, 3));
/* 206 */     ThaumcraftApi.registerObjectTag(new ItemStack(BlockRegistry.pamapricotSapling), new AspectList().add(Aspect.TREE, 1).add(Aspect.PLANT, 1).add(Aspect.PLANT, 1));
/* 207 */     ThaumcraftApi.registerObjectTag(new ItemStack(BlockRegistry.pamAvocado), new AspectList().add(Aspect.CROP, 3));
/* 208 */     ThaumcraftApi.registerObjectTag(new ItemStack(BlockRegistry.pamavocadoSapling), new AspectList().add(Aspect.TREE, 1).add(Aspect.PLANT, 1).add(Aspect.PLANT, 1));
/* 209 */     ThaumcraftApi.registerObjectTag(new ItemStack(BlockRegistry.pamBanana), new AspectList().add(Aspect.CROP, 3));
/* 210 */     ThaumcraftApi.registerObjectTag(new ItemStack(BlockRegistry.pambananaSapling), new AspectList().add(Aspect.TREE, 1).add(Aspect.PLANT, 1).add(Aspect.PLANT, 1));
/* 211 */     ThaumcraftApi.registerObjectTag(new ItemStack(BlockRegistry.pamCashew), new AspectList().add(Aspect.CROP, 3));
/* 212 */     ThaumcraftApi.registerObjectTag(new ItemStack(BlockRegistry.pamcashewSapling), new AspectList().add(Aspect.TREE, 1).add(Aspect.PLANT, 1).add(Aspect.PLANT, 1));
/* 213 */     ThaumcraftApi.registerObjectTag(new ItemStack(BlockRegistry.pamCherry), new AspectList().add(Aspect.CROP, 3));
/* 214 */     ThaumcraftApi.registerObjectTag(new ItemStack(BlockRegistry.pamcherrySapling), new AspectList().add(Aspect.TREE, 1).add(Aspect.PLANT, 1).add(Aspect.PLANT, 1));
/* 215 */     ThaumcraftApi.registerObjectTag(new ItemStack(BlockRegistry.pamChestnut), new AspectList().add(Aspect.CROP, 3));
/* 216 */     ThaumcraftApi.registerObjectTag(new ItemStack(BlockRegistry.pamchestnutSapling), new AspectList().add(Aspect.TREE, 1).add(Aspect.PLANT, 1).add(Aspect.PLANT, 1));
/* 217 */     ThaumcraftApi.registerObjectTag(new ItemStack(BlockRegistry.pamCinnamon), new AspectList().add(Aspect.CROP, 3));
/* 218 */     ThaumcraftApi.registerObjectTag(new ItemStack(BlockRegistry.pamcinnamonSapling), new AspectList().add(Aspect.TREE, 1).add(Aspect.PLANT, 1).add(Aspect.PLANT, 1));
/* 219 */     ThaumcraftApi.registerObjectTag(new ItemStack(BlockRegistry.pamCoconut), new AspectList().add(Aspect.CROP, 3));
/* 220 */     ThaumcraftApi.registerObjectTag(new ItemStack(BlockRegistry.pamcoconutSapling), new AspectList().add(Aspect.TREE, 1).add(Aspect.PLANT, 1).add(Aspect.PLANT, 1));
/* 221 */     ThaumcraftApi.registerObjectTag(new ItemStack(BlockRegistry.pamDate), new AspectList().add(Aspect.CROP, 3));
/* 222 */     ThaumcraftApi.registerObjectTag(new ItemStack(BlockRegistry.pamdateSapling), new AspectList().add(Aspect.TREE, 1).add(Aspect.PLANT, 1).add(Aspect.PLANT, 1));
/* 223 */     ThaumcraftApi.registerObjectTag(new ItemStack(BlockRegistry.pamDragonfruit), new AspectList().add(Aspect.CROP, 3));
/* 224 */     ThaumcraftApi.registerObjectTag(new ItemStack(BlockRegistry.pamdragonfruitSapling), new AspectList().add(Aspect.TREE, 1).add(Aspect.PLANT, 1).add(Aspect.PLANT, 1));
/* 225 */     ThaumcraftApi.registerObjectTag(new ItemStack(BlockRegistry.pamDurian), new AspectList().add(Aspect.CROP, 3));
/* 226 */     ThaumcraftApi.registerObjectTag(new ItemStack(BlockRegistry.pamdurianSapling), new AspectList().add(Aspect.TREE, 1).add(Aspect.PLANT, 1).add(Aspect.PLANT, 1));
/* 227 */     ThaumcraftApi.registerObjectTag(new ItemStack(BlockRegistry.pamFig), new AspectList().add(Aspect.CROP, 3));
/* 228 */     ThaumcraftApi.registerObjectTag(new ItemStack(BlockRegistry.pamfigSapling), new AspectList().add(Aspect.TREE, 1).add(Aspect.PLANT, 1).add(Aspect.PLANT, 1));
/* 229 */     ThaumcraftApi.registerObjectTag(new ItemStack(BlockRegistry.pamGrapefruit), new AspectList().add(Aspect.CROP, 3));
/* 230 */     ThaumcraftApi.registerObjectTag(new ItemStack(BlockRegistry.pamgrapefruitSapling), new AspectList().add(Aspect.TREE, 1).add(Aspect.PLANT, 1).add(Aspect.PLANT, 1));
/* 231 */     ThaumcraftApi.registerObjectTag(new ItemStack(BlockRegistry.pamLemon), new AspectList().add(Aspect.CROP, 3));
/* 232 */     ThaumcraftApi.registerObjectTag(new ItemStack(BlockRegistry.pamlemonSapling), new AspectList().add(Aspect.TREE, 1).add(Aspect.PLANT, 1).add(Aspect.PLANT, 1));
/* 233 */     ThaumcraftApi.registerObjectTag(new ItemStack(BlockRegistry.pamLime), new AspectList().add(Aspect.CROP, 3));
/* 234 */     ThaumcraftApi.registerObjectTag(new ItemStack(BlockRegistry.pamlimeSapling), new AspectList().add(Aspect.TREE, 1).add(Aspect.PLANT, 1).add(Aspect.PLANT, 1));
/* 235 */     ThaumcraftApi.registerObjectTag(new ItemStack(BlockRegistry.pamMango), new AspectList().add(Aspect.CROP, 3));
/* 236 */     ThaumcraftApi.registerObjectTag(new ItemStack(BlockRegistry.pammangoSapling), new AspectList().add(Aspect.TREE, 1).add(Aspect.PLANT, 1).add(Aspect.PLANT, 1));
/* 237 */     ThaumcraftApi.registerObjectTag(new ItemStack(BlockRegistry.pamMaple), new AspectList().add(Aspect.CROP, 3));
/* 238 */     ThaumcraftApi.registerObjectTag(new ItemStack(BlockRegistry.pammapleSapling), new AspectList().add(Aspect.TREE, 1).add(Aspect.PLANT, 1).add(Aspect.PLANT, 1));
/* 239 */     ThaumcraftApi.registerObjectTag(new ItemStack(BlockRegistry.pamNutmeg), new AspectList().add(Aspect.CROP, 3));
/* 240 */     ThaumcraftApi.registerObjectTag(new ItemStack(BlockRegistry.pamnutmegSapling), new AspectList().add(Aspect.TREE, 1).add(Aspect.PLANT, 1).add(Aspect.PLANT, 1));
/* 241 */     ThaumcraftApi.registerObjectTag(new ItemStack(BlockRegistry.pamOlive), new AspectList().add(Aspect.CROP, 3));
/* 242 */     ThaumcraftApi.registerObjectTag(new ItemStack(BlockRegistry.pamoliveSapling), new AspectList().add(Aspect.TREE, 1).add(Aspect.PLANT, 1).add(Aspect.PLANT, 1));
/* 243 */     ThaumcraftApi.registerObjectTag(new ItemStack(BlockRegistry.pamOrange), new AspectList().add(Aspect.CROP, 3));
/* 244 */     ThaumcraftApi.registerObjectTag(new ItemStack(BlockRegistry.pamorangeSapling), new AspectList().add(Aspect.TREE, 1).add(Aspect.PLANT, 1).add(Aspect.PLANT, 1));
/* 245 */     ThaumcraftApi.registerObjectTag(new ItemStack(BlockRegistry.pamPapaya), new AspectList().add(Aspect.CROP, 3));
/* 246 */     ThaumcraftApi.registerObjectTag(new ItemStack(BlockRegistry.pampapayaSapling), new AspectList().add(Aspect.TREE, 1).add(Aspect.PLANT, 1).add(Aspect.PLANT, 1));
/* 247 */     ThaumcraftApi.registerObjectTag(new ItemStack(BlockRegistry.pamPaperbark), new AspectList().add(Aspect.CROP, 3));
/* 248 */     ThaumcraftApi.registerObjectTag(new ItemStack(BlockRegistry.pampaperbarkSapling), new AspectList().add(Aspect.TREE, 1).add(Aspect.PLANT, 1).add(Aspect.PLANT, 1));
/* 249 */     ThaumcraftApi.registerObjectTag(new ItemStack(BlockRegistry.pamPeach), new AspectList().add(Aspect.CROP, 3));
/* 250 */     ThaumcraftApi.registerObjectTag(new ItemStack(BlockRegistry.pampeachSapling), new AspectList().add(Aspect.TREE, 1).add(Aspect.PLANT, 1).add(Aspect.PLANT, 1));
/* 251 */     ThaumcraftApi.registerObjectTag(new ItemStack(BlockRegistry.pamPear), new AspectList().add(Aspect.CROP, 3));
/* 252 */     ThaumcraftApi.registerObjectTag(new ItemStack(BlockRegistry.pampearSapling), new AspectList().add(Aspect.TREE, 1).add(Aspect.PLANT, 1).add(Aspect.PLANT, 1));
/* 253 */     ThaumcraftApi.registerObjectTag(new ItemStack(BlockRegistry.pamPecan), new AspectList().add(Aspect.CROP, 3));
/* 254 */     ThaumcraftApi.registerObjectTag(new ItemStack(BlockRegistry.pampecanSapling), new AspectList().add(Aspect.TREE, 1).add(Aspect.PLANT, 1).add(Aspect.PLANT, 1));
/* 255 */     ThaumcraftApi.registerObjectTag(new ItemStack(BlockRegistry.pamPeppercorn), new AspectList().add(Aspect.CROP, 3));
/* 256 */     ThaumcraftApi.registerObjectTag(new ItemStack(BlockRegistry.pampeppercornSapling), new AspectList().add(Aspect.TREE, 1).add(Aspect.PLANT, 1).add(Aspect.PLANT, 1));
/* 257 */     ThaumcraftApi.registerObjectTag(new ItemStack(BlockRegistry.pamPersimmon), new AspectList().add(Aspect.CROP, 3));
/* 258 */     ThaumcraftApi.registerObjectTag(new ItemStack(BlockRegistry.pampersimmonSapling), new AspectList().add(Aspect.TREE, 1).add(Aspect.PLANT, 1).add(Aspect.PLANT, 1));
/* 259 */     ThaumcraftApi.registerObjectTag(new ItemStack(BlockRegistry.pamPistachio), new AspectList().add(Aspect.CROP, 3));
/* 260 */     ThaumcraftApi.registerObjectTag(new ItemStack(BlockRegistry.pampistachioSapling), new AspectList().add(Aspect.TREE, 1).add(Aspect.PLANT, 1).add(Aspect.PLANT, 1));
/* 261 */     ThaumcraftApi.registerObjectTag(new ItemStack(BlockRegistry.pamPlum), new AspectList().add(Aspect.CROP, 3));
/* 262 */     ThaumcraftApi.registerObjectTag(new ItemStack(BlockRegistry.pamplumSapling), new AspectList().add(Aspect.TREE, 1).add(Aspect.PLANT, 1).add(Aspect.PLANT, 1));
/* 263 */     ThaumcraftApi.registerObjectTag(new ItemStack(BlockRegistry.pamPomegranate), new AspectList().add(Aspect.CROP, 3));
/* 264 */     ThaumcraftApi.registerObjectTag(new ItemStack(BlockRegistry.pampomegranateSapling), new AspectList().add(Aspect.TREE, 1).add(Aspect.PLANT, 1).add(Aspect.PLANT, 1));
/* 265 */     ThaumcraftApi.registerObjectTag(new ItemStack(BlockRegistry.pamStarfruit), new AspectList().add(Aspect.CROP, 3));
/* 266 */     ThaumcraftApi.registerObjectTag(new ItemStack(BlockRegistry.pamstarfruitSapling), new AspectList().add(Aspect.TREE, 1).add(Aspect.PLANT, 1).add(Aspect.PLANT, 1));
/* 267 */     ThaumcraftApi.registerObjectTag(new ItemStack(BlockRegistry.pamVanillabean), new AspectList().add(Aspect.CROP, 3));
/* 268 */     ThaumcraftApi.registerObjectTag(new ItemStack(BlockRegistry.pamvanillabeanSapling), new AspectList().add(Aspect.TREE, 1).add(Aspect.PLANT, 1).add(Aspect.PLANT, 1));
/* 269 */     ThaumcraftApi.registerObjectTag(new ItemStack(BlockRegistry.pamWalnut), new AspectList().add(Aspect.CROP, 3));
/* 270 */     ThaumcraftApi.registerObjectTag(new ItemStack(BlockRegistry.pamwalnutSapling), new AspectList().add(Aspect.TREE, 1).add(Aspect.PLANT, 1).add(Aspect.PLANT, 1));
/* 271 */     ThaumcraftApi.registerObjectTag(new ItemStack(BlockRegistry.pamGooseberry), new AspectList().add(Aspect.CROP, 3));
/* 272 */     ThaumcraftApi.registerObjectTag(new ItemStack(BlockRegistry.pamgooseberrySapling), new AspectList().add(Aspect.TREE, 1).add(Aspect.PLANT, 1).add(Aspect.PLANT, 1));
/*     */     
/* 274 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.asparagusItem), new AspectList().add(Aspect.CROP, 2).add(Aspect.HUNGER, 1));
/* 275 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.asparagusseedItem), new AspectList().add(Aspect.PLANT, 1));
/* 276 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.grilledasparagusItem), new AspectList().add(Aspect.CROP, 1).add(Aspect.HUNGER, 2));
/* 277 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.barleyItem), new AspectList().add(Aspect.CROP, 2).add(Aspect.HUNGER, 1));
/* 278 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.barleyseedItem), new AspectList().add(Aspect.PLANT, 1));
/* 279 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.beanItem), new AspectList().add(Aspect.CROP, 2).add(Aspect.HUNGER, 1));
/* 280 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.beanseedItem), new AspectList().add(Aspect.PLANT, 1));
/* 281 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.beetItem), new AspectList().add(Aspect.CROP, 1).add(Aspect.HUNGER, 1).add(Aspect.EARTH, 1));
/* 282 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.beetseedItem), new AspectList().add(Aspect.PLANT, 1));
/* 283 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.broccoliItem), new AspectList().add(Aspect.CROP, 2).add(Aspect.HUNGER, 1));
/* 284 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.broccoliseedItem), new AspectList().add(Aspect.PLANT, 1));
/* 285 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.cauliflowerItem), new AspectList().add(Aspect.CROP, 2).add(Aspect.HUNGER, 1));
/* 286 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.cauliflowerseedItem), new AspectList().add(Aspect.PLANT, 1));
/* 287 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.celeryItem), new AspectList().add(Aspect.CROP, 1).add(Aspect.HUNGER, 1).add(Aspect.WATER, 1));
/* 288 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.celeryseedItem), new AspectList().add(Aspect.PLANT, 1));
/* 289 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.cranberryItem), new AspectList().add(Aspect.CROP, 1).add(Aspect.HUNGER, 1).add(Aspect.WATER, 1));
/* 290 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.cranberryseedItem), new AspectList().add(Aspect.PLANT, 1));
/* 291 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.garlicItem), new AspectList().add(Aspect.CROP, 2).add(Aspect.HUNGER, 1));
/* 292 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.garlicseedItem), new AspectList().add(Aspect.PLANT, 1));
/* 293 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.gingerItem), new AspectList().add(Aspect.CROP, 2).add(Aspect.HUNGER, 1));
/* 294 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.gingerseedItem), new AspectList().add(Aspect.PLANT, 1));
/* 295 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.leekItem), new AspectList().add(Aspect.CROP, 2).add(Aspect.HUNGER, 1));
/* 296 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.leekseedItem), new AspectList().add(Aspect.PLANT, 1));
/* 297 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.lettuceItem), new AspectList().add(Aspect.CROP, 2).add(Aspect.HUNGER, 1));
/* 298 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.lettuceseedItem), new AspectList().add(Aspect.PLANT, 1));
/* 299 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.oatsItem), new AspectList().add(Aspect.CROP, 2).add(Aspect.HUNGER, 1));
/* 300 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.oatsseedItem), new AspectList().add(Aspect.PLANT, 1));
/* 301 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.onionItem), new AspectList().add(Aspect.CROP, 1).add(Aspect.HUNGER, 1).add(Aspect.EARTH, 1));
/* 302 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.onionseedItem), new AspectList().add(Aspect.PLANT, 1));
/* 303 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.parsnipItem), new AspectList().add(Aspect.CROP, 1).add(Aspect.HUNGER, 1).add(Aspect.EARTH, 1));
/* 304 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.parsnipseedItem), new AspectList().add(Aspect.PLANT, 1));
/* 305 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.peanutItem), new AspectList().add(Aspect.CROP, 1).add(Aspect.HUNGER, 1).add(Aspect.EARTH, 1));
/* 306 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.peanutseedItem), new AspectList().add(Aspect.PLANT, 1));
/* 307 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.pineappleItem), new AspectList().add(Aspect.CROP, 2).add(Aspect.HUNGER, 1));
/* 308 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.pineappleseedItem), new AspectList().add(Aspect.PLANT, 1));
/* 309 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.radishItem), new AspectList().add(Aspect.CROP, 2).add(Aspect.HUNGER, 1));
/* 310 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.radishseedItem), new AspectList().add(Aspect.PLANT, 1));
/* 311 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.riceItem), new AspectList().add(Aspect.CROP, 2).add(Aspect.HUNGER, 1));
/* 312 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.riceseedItem), new AspectList().add(Aspect.PLANT, 1));
/* 313 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.ricecakeItem), new AspectList().add(Aspect.CROP, 1).add(Aspect.HUNGER, 2));
/* 314 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.rutabagaItem), new AspectList().add(Aspect.CROP, 1).add(Aspect.HUNGER, 1).add(Aspect.EARTH, 1));
/* 315 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.rutabagaseedItem), new AspectList().add(Aspect.PLANT, 1));
/* 316 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.ryeItem), new AspectList().add(Aspect.CROP, 2).add(Aspect.HUNGER, 1));
/* 317 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.ryeseedItem), new AspectList().add(Aspect.PLANT, 1));
/* 318 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.scallionItem), new AspectList().add(Aspect.CROP, 2).add(Aspect.HUNGER, 1));
/* 319 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.scallionseedItem), new AspectList().add(Aspect.PLANT, 1));
/* 320 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.soybeanItem), new AspectList().add(Aspect.CROP, 1).add(Aspect.HUNGER, 1).add(Aspect.EXCHANGE, 1));
/* 321 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.soybeanseedItem), new AspectList().add(Aspect.PLANT, 1));
/* 322 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.spiceleafItem), new AspectList().add(Aspect.CROP, 2).add(Aspect.HUNGER, 1));
/* 323 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.spiceleafseedItem), new AspectList().add(Aspect.PLANT, 1));
/* 324 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.spinachItem), new AspectList().add(Aspect.CROP, 2).add(Aspect.HUNGER, 1));
/* 325 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.spinachseedItem), new AspectList().add(Aspect.PLANT, 1));
/* 326 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.sunflowerseedsItem), new AspectList().add(Aspect.CROP, 2).add(Aspect.HUNGER, 1));
/* 327 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.sweetpotatoItem), new AspectList().add(Aspect.CROP, 1).add(Aspect.HUNGER, 1).add(Aspect.EARTH, 1));
/* 328 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.sweetpotatoseedItem), new AspectList().add(Aspect.PLANT, 1));
/* 329 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.bakedsweetpotatoItem), new AspectList().add(Aspect.CROP, 1).add(Aspect.HUNGER, 2));
/* 330 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.tealeafItem), new AspectList().add(Aspect.CROP, 2).add(Aspect.HUNGER, 1));
/* 331 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.teaseedItem), new AspectList().add(Aspect.PLANT, 1));
/* 332 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.teaItem), new AspectList().add(Aspect.CROP, 1).add(Aspect.HUNGER, 2));
/* 333 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.turnipItem), new AspectList().add(Aspect.CROP, 1).add(Aspect.HUNGER, 1).add(Aspect.EARTH, 1));
/* 334 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.turnipseedItem), new AspectList().add(Aspect.PLANT, 1));
/* 335 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.whitemushroomItem), new AspectList().add(Aspect.CROP, 1).add(Aspect.HUNGER, 1).add(Aspect.DARKNESS, 1));
/* 336 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.whitemushroomseedItem), new AspectList().add(Aspect.PLANT, 1));
/*     */     
/* 338 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.artichokeItem), new AspectList().add(Aspect.CROP, 2).add(Aspect.HUNGER, 1));
/* 339 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.artichokeseedItem), new AspectList().add(Aspect.PLANT, 1));
/* 340 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.bellpepperItem), new AspectList().add(Aspect.CROP, 2).add(Aspect.HUNGER, 1));
/* 341 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.bellpepperseedItem), new AspectList().add(Aspect.PLANT, 1));
/* 342 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.blackberryItem), new AspectList().add(Aspect.CROP, 2).add(Aspect.HUNGER, 1));
/* 343 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.blackberryseedItem), new AspectList().add(Aspect.PLANT, 1));
/* 344 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.blueberryItem), new AspectList().add(Aspect.CROP, 2).add(Aspect.HUNGER, 1));
/* 345 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.blueberryseedItem), new AspectList().add(Aspect.PLANT, 1));
/* 346 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.brusselsproutItem), new AspectList().add(Aspect.CROP, 2).add(Aspect.HUNGER, 1));
/* 347 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.brusselsproutseedItem), new AspectList().add(Aspect.PLANT, 1));
/* 348 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.cabbageItem), new AspectList().add(Aspect.CROP, 2).add(Aspect.HUNGER, 1));
/* 349 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.cabbageseedItem), new AspectList().add(Aspect.PLANT, 1));
/* 350 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.cactusfruitItem), new AspectList().add(Aspect.CROP, 1).add(Aspect.HUNGER, 1).add(Aspect.WATER, 1));
/* 351 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.cactusfruitseedItem), new AspectList().add(Aspect.PLANT, 1));
/* 352 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.candleberryItem), new AspectList().add(Aspect.CROP, 2).add(Aspect.ORDER, 1));
/* 353 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.candleberryseedItem), new AspectList().add(Aspect.PLANT, 1));
/* 354 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.waxItem), new AspectList().add(Aspect.ORDER, 2).add(Aspect.CRAFT, 1));
/* 355 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.cantaloupeItem), new AspectList().add(Aspect.CROP, 2).add(Aspect.HUNGER, 1));
/* 356 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.cantaloupeseedItem), new AspectList().add(Aspect.PLANT, 1));
/* 357 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.chilipepperItem), new AspectList().add(Aspect.CROP, 1).add(Aspect.HUNGER, 1).add(Aspect.FIRE, 1));
/* 358 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.chilipepperseedItem), new AspectList().add(Aspect.PLANT, 1));
/* 359 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.coffeebeanItem), new AspectList().add(Aspect.CROP, 2).add(Aspect.HUNGER, 1));
/* 360 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.coffeeseedItem), new AspectList().add(Aspect.PLANT, 1));
/* 361 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.coffeeItem), new AspectList().add(Aspect.CROP, 1).add(Aspect.HUNGER, 2));
/* 362 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.cornItem), new AspectList().add(Aspect.CROP, 2).add(Aspect.HUNGER, 1));
/* 363 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.cornseedItem), new AspectList().add(Aspect.PLANT, 1));
/* 364 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.popcornItem), new AspectList().add(Aspect.CROP, 1).add(Aspect.HUNGER, 2));
/* 365 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.cottonItem), new AspectList().add(Aspect.CROP, 2).add(Aspect.CLOTH, 1));
/* 366 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.cottonseedItem), new AspectList().add(Aspect.PLANT, 1));
/* 367 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.wovencottonItem), new AspectList().add(Aspect.CLOTH, 2).add(Aspect.CRAFT, 1));
/* 368 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.cucumberItem), new AspectList().add(Aspect.CROP, 2).add(Aspect.HUNGER, 1));
/* 369 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.cucumberseedItem), new AspectList().add(Aspect.PLANT, 1));
/* 370 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.eggplantItem), new AspectList().add(Aspect.CROP, 2).add(Aspect.HUNGER, 1));
/* 371 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.eggplantseedItem), new AspectList().add(Aspect.PLANT, 1));
/* 372 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.grilledeggplantItem), new AspectList().add(Aspect.CROP, 1).add(Aspect.HUNGER, 2));
/* 373 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.grapeItem), new AspectList().add(Aspect.CROP, 2).add(Aspect.HUNGER, 1));
/* 374 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.grapeseedItem), new AspectList().add(Aspect.PLANT, 1));
/* 375 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.raisinsItem), new AspectList().add(Aspect.CROP, 1).add(Aspect.HUNGER, 2));
/* 376 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.kiwiItem), new AspectList().add(Aspect.CROP, 2).add(Aspect.HUNGER, 1));
/* 377 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.kiwiseedItem), new AspectList().add(Aspect.PLANT, 1));
/* 378 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.mustardseedsItem), new AspectList().add(Aspect.CROP, 2).add(Aspect.HUNGER, 1));
/* 379 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.mustardseedItem), new AspectList().add(Aspect.PLANT, 1));
/* 380 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.okraItem), new AspectList().add(Aspect.CROP, 2).add(Aspect.HUNGER, 1));
/* 381 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.okraseedItem), new AspectList().add(Aspect.PLANT, 1));
/* 382 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.peasItem), new AspectList().add(Aspect.CROP, 2).add(Aspect.HUNGER, 1));
/* 383 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.peasseedItem), new AspectList().add(Aspect.PLANT, 1));
/* 384 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.raspberryItem), new AspectList().add(Aspect.CROP, 2).add(Aspect.HUNGER, 1));
/* 385 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.raspberryseedItem), new AspectList().add(Aspect.PLANT, 1));
/* 386 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.rhubarbItem), new AspectList().add(Aspect.CROP, 2).add(Aspect.HUNGER, 1));
/* 387 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.rhubarbseedItem), new AspectList().add(Aspect.PLANT, 1));
/* 388 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.seaweedItem), new AspectList().add(Aspect.CROP, 1).add(Aspect.HUNGER, 1).add(Aspect.WATER, 1));
/* 389 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.seaweedseedItem), new AspectList().add(Aspect.PLANT, 1));
/* 390 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.strawberryItem), new AspectList().add(Aspect.CROP, 2).add(Aspect.HUNGER, 1));
/* 391 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.strawberryseedItem), new AspectList().add(Aspect.PLANT, 1));
/* 392 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.tomatoItem), new AspectList().add(Aspect.CROP, 2).add(Aspect.HUNGER, 1));
/* 393 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.tomatoseedItem), new AspectList().add(Aspect.PLANT, 1));
/* 394 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.wintersquashItem), new AspectList().add(Aspect.CROP, 2).add(Aspect.HUNGER, 1));
/* 395 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.wintersquashseedItem), new AspectList().add(Aspect.PLANT, 1));
/* 396 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.zucchiniItem), new AspectList().add(Aspect.CROP, 2).add(Aspect.HUNGER, 1));
/* 397 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.zucchiniseedItem), new AspectList().add(Aspect.PLANT, 1));
/* 398 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.bambooshootItem), new AspectList().add(Aspect.CROP, 2).add(Aspect.HUNGER, 1));
/* 399 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.bambooshootseedItem), new AspectList().add(Aspect.PLANT, 1));
/* 400 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.curryleafItem), new AspectList().add(Aspect.CROP, 2).add(Aspect.HUNGER, 1));
/* 401 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.curryleafseedItem), new AspectList().add(Aspect.PLANT, 1));
/* 402 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.sesameseedsItem), new AspectList().add(Aspect.CROP, 2).add(Aspect.HUNGER, 1));
/* 403 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.sesameseedsseedItem), new AspectList().add(Aspect.PLANT, 1));
/* 404 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.waterchestnutItem), new AspectList().add(Aspect.CROP, 2).add(Aspect.HUNGER, 1));
/* 405 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.waterchestnutseedItem), new AspectList().add(Aspect.PLANT, 1));
/*     */     
/* 407 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.almondItem), new AspectList().add(Aspect.CROP, 2).add(Aspect.HUNGER, 1));
/* 408 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.avocadoItem), new AspectList().add(Aspect.CROP, 2).add(Aspect.HUNGER, 1));
/* 409 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.bananaItem), new AspectList().add(Aspect.CROP, 2).add(Aspect.HUNGER, 1));
/* 410 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.cashewItem), new AspectList().add(Aspect.CROP, 2).add(Aspect.HUNGER, 1));
/* 411 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.cherryItem), new AspectList().add(Aspect.CROP, 2).add(Aspect.HUNGER, 1));
/* 412 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.cinnamonItem), new AspectList().add(Aspect.CROP, 2).add(Aspect.HUNGER, 1));
/* 413 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.chestnutItem), new AspectList().add(Aspect.CROP, 2).add(Aspect.HUNGER, 1));
/* 414 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.coconutItem), new AspectList().add(Aspect.CROP, 1).add(Aspect.HUNGER, 1).add(Aspect.WATER, 1));
/* 415 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.toastedcoconutItem), new AspectList().add(Aspect.CROP, 1).add(Aspect.HUNGER, 2));
/* 416 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.dateItem), new AspectList().add(Aspect.CROP, 2).add(Aspect.HUNGER, 1));
/* 417 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.dragonfruitItem), new AspectList().add(Aspect.CROP, 2).add(Aspect.HUNGER, 1));
/* 418 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.figItem), new AspectList().add(Aspect.CROP, 2).add(Aspect.HUNGER, 1));
/* 419 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.grapefruitItem), new AspectList().add(Aspect.CROP, 2).add(Aspect.HUNGER, 1));
/* 420 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.lemonItem), new AspectList().add(Aspect.CROP, 2).add(Aspect.HUNGER, 1));
/* 421 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.limeItem), new AspectList().add(Aspect.CROP, 2).add(Aspect.HUNGER, 1));
/* 422 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.mangoItem), new AspectList().add(Aspect.CROP, 2).add(Aspect.HUNGER, 1));
/* 423 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.maplesyrupItem), new AspectList().add(Aspect.CROP, 2).add(Aspect.HUNGER, 1));
/* 424 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.nutmegItem), new AspectList().add(Aspect.CROP, 2).add(Aspect.HUNGER, 1));
/* 425 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.oliveItem), new AspectList().add(Aspect.CROP, 2).add(Aspect.HUNGER, 1));
/* 426 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.orangeItem), new AspectList().add(Aspect.CROP, 2).add(Aspect.HUNGER, 1));
/* 427 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.papayaItem), new AspectList().add(Aspect.CROP, 2).add(Aspect.HUNGER, 1));
/* 428 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.peachItem), new AspectList().add(Aspect.CROP, 2).add(Aspect.HUNGER, 1));
/* 429 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.pearItem), new AspectList().add(Aspect.CROP, 2).add(Aspect.HUNGER, 1));
/* 430 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.peppercornItem), new AspectList().add(Aspect.CROP, 2).add(Aspect.HUNGER, 1));
/* 431 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.persimmonItem), new AspectList().add(Aspect.CROP, 2).add(Aspect.HUNGER, 1));
/* 432 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.pistachioItem), new AspectList().add(Aspect.CROP, 2).add(Aspect.HUNGER, 1));
/* 433 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.plumItem), new AspectList().add(Aspect.CROP, 2).add(Aspect.HUNGER, 1));
/* 434 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.pomegranateItem), new AspectList().add(Aspect.CROP, 2).add(Aspect.HUNGER, 1));
/* 435 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.starfruitItem), new AspectList().add(Aspect.CROP, 2).add(Aspect.HUNGER, 1));
/* 436 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.vanillabeanItem), new AspectList().add(Aspect.CROP, 2).add(Aspect.HUNGER, 1));
/* 437 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.vanillaItem), new AspectList().add(Aspect.CROP, 1).add(Aspect.HUNGER, 2));
/* 438 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.walnutItem), new AspectList().add(Aspect.CROP, 2).add(Aspect.HUNGER, 1));
/* 439 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.gooseberryItem), new AspectList().add(Aspect.CROP, 2).add(Aspect.HUNGER, 1));
/*     */     
/* 441 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.ediblerootItem), new AspectList().add(Aspect.CROP, 1).add(Aspect.HUNGER, 1).add(Aspect.EARTH, 1));
/*     */     
/* 443 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.freshwaterItem), new AspectList().add(Aspect.WATER, 1));
/* 444 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.freshmilkItem), new AspectList().add(Aspect.HEAL, 1));
/*     */     
/* 446 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.muttonrawItem), new AspectList().add(Aspect.FLESH, 3).add(Aspect.LIFE, 1).add(Aspect.BEAST, 1));
/* 447 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.muttoncookedItem), new AspectList().add(Aspect.CRAFT, 1).add(Aspect.FLESH, 3).add(Aspect.HUNGER, 3));
/* 448 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.calamarirawItem), new AspectList().add(Aspect.FLESH, 3).add(Aspect.LIFE, 1).add(Aspect.WATER, 1));
/* 449 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.calamaricookedItem), new AspectList().add(Aspect.CRAFT, 1).add(Aspect.FLESH, 4).add(Aspect.HUNGER, 3));
/*     */     
/* 451 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.anchovyrawItem), new AspectList().add(Aspect.FLESH, 3).add(Aspect.LIFE, 1).add(Aspect.WATER, 1));
/* 452 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.bassrawItem), new AspectList().add(Aspect.FLESH, 3).add(Aspect.LIFE, 1).add(Aspect.WATER, 1));
/* 453 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.carprawItem), new AspectList().add(Aspect.FLESH, 3).add(Aspect.LIFE, 1).add(Aspect.WATER, 1));
/* 454 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.catfishrawItem), new AspectList().add(Aspect.FLESH, 3).add(Aspect.LIFE, 1).add(Aspect.WATER, 1));
/* 455 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.charrrawItem), new AspectList().add(Aspect.FLESH, 3).add(Aspect.LIFE, 1).add(Aspect.WATER, 1));
/* 456 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.clamrawItem), new AspectList().add(Aspect.FLESH, 3).add(Aspect.LIFE, 1).add(Aspect.WATER, 1));
/* 457 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.crabrawItem), new AspectList().add(Aspect.FLESH, 3).add(Aspect.LIFE, 1).add(Aspect.WATER, 1));
/* 458 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.crayfishrawItem), new AspectList().add(Aspect.FLESH, 3).add(Aspect.LIFE, 1).add(Aspect.WATER, 1));
/* 459 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.eelrawItem), new AspectList().add(Aspect.FLESH, 3).add(Aspect.LIFE, 1).add(Aspect.WATER, 1));
/* 460 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.frograwItem), new AspectList().add(Aspect.FLESH, 3).add(Aspect.LIFE, 1).add(Aspect.WATER, 1));
/* 461 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.grouperrawItem), new AspectList().add(Aspect.FLESH, 3).add(Aspect.LIFE, 1).add(Aspect.WATER, 1));
/* 462 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.herringrawItem), new AspectList().add(Aspect.FLESH, 3).add(Aspect.LIFE, 1).add(Aspect.WATER, 1));
/* 463 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.jellyfishrawItem), new AspectList().add(Aspect.SLIME, 3).add(Aspect.LIFE, 1).add(Aspect.WATER, 1));
/* 464 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.mudfishrawItem), new AspectList().add(Aspect.FLESH, 3).add(Aspect.LIFE, 1).add(Aspect.WATER, 1));
/* 465 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.octopusrawItem), new AspectList().add(Aspect.FLESH, 3).add(Aspect.LIFE, 1).add(Aspect.WATER, 1));
/* 466 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.perchrawItem), new AspectList().add(Aspect.FLESH, 3).add(Aspect.LIFE, 1).add(Aspect.WATER, 1));
/* 467 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.scalloprawItem), new AspectList().add(Aspect.FLESH, 3).add(Aspect.LIFE, 1).add(Aspect.WATER, 1));
/* 468 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.shrimprawItem), new AspectList().add(Aspect.FLESH, 3).add(Aspect.LIFE, 1).add(Aspect.WATER, 1));
/* 469 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.snailrawItem), new AspectList().add(Aspect.FLESH, 3).add(Aspect.LIFE, 1).add(Aspect.WATER, 1));
/* 470 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.snapperrawItem), new AspectList().add(Aspect.FLESH, 3).add(Aspect.LIFE, 1).add(Aspect.WATER, 1));
/* 471 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.tilapiarawItem), new AspectList().add(Aspect.FLESH, 3).add(Aspect.LIFE, 1).add(Aspect.WATER, 1));
/* 472 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.troutrawItem), new AspectList().add(Aspect.FLESH, 3).add(Aspect.LIFE, 1).add(Aspect.WATER, 1));
/* 473 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.tunarawItem), new AspectList().add(Aspect.FLESH, 3).add(Aspect.LIFE, 1).add(Aspect.WATER, 1));
/* 474 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.turtlerawItem), new AspectList().add(Aspect.FLESH, 3).add(Aspect.LIFE, 1).add(Aspect.WATER, 1));
/* 475 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.walleyerawItem), new AspectList().add(Aspect.FLESH, 3).add(Aspect.LIFE, 1).add(Aspect.WATER, 1));
/* 476 */     ThaumcraftApi.registerObjectTag(new ItemStack(ItemRegistry.greenheartfishItem), new AspectList().add(Aspect.FLESH, 3).add(Aspect.LIFE, 1).add(Aspect.WATER, 1));
/*     */   }
/*     */ }


/* Location:              C:\Users\Modding\Desktop\Pam's HarvestCraft 1.7.10k.deobf.jar!\com\pam\harvestcraft\PamThaumcraftAspectsList.class
 * Java compiler version: 6 (50.0)
 * JD-Core Version:       0.7.1
 */